app = "claude-computeruse"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PUBLIC_HOST = "claude-computeruse.fly.dev"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8501
  protocol = "tcp"
  [[services.ports]]
    port = 8501
    handlers = ["tls", "http"]

[[services]]
  internal_port = 6080
  protocol = "tcp"
  [[services.ports]]
    port = 6080
    handlers = ["tls", "http"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
